export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_FAILED';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_PRODUCT_START = 'PURCHASE_PRODUCT_START';
export const PURCHASE_PRODUCT_SUCCESS = 'PURCHASE_PRODUCT_SUCCESS';
export const PURCHASE_PRODUCT_FAIL = 'PURCHASE_PRODUCT_FAIL';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const REMOVE_ALL_ORDER = 'REMOVE_ORDER';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';